# Generated by Django 5.0.6 on 2024-06-05 13:33

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('banking', 'Banking'), ('education', 'Education'), ('IT', 'IT'), ('law', 'Law'), ('sales', 'Sales'), ('real_estate', 'Real Estate'), ('human_resouroces', 'Human Resouroces'), ('logistics', 'Logistics'), ('customer_service', 'Customer Service'), ('art', 'Art')], max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=511)),
                ('description', django_quill.fields.QuillField(verbose_name='description')),
                ('offered_pay', models.CharField(max_length=31)),
                ('categories', models.ManyToManyField(to='job_offers.category')),
            ],
        ),
    ]
