# Generated by Django 5.0.6 on 2024-09-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_alter_category_id_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='offered_pay',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.IntegerField(default=5000, verbose_name='salary'),
        ),
    ]
